version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: to_do_mysql
    environment:
        MYSQL_ROOT_PASSWORD: senha
        MYSQL_DATABASE: to_do_db
    ports:
        - "3307:3306"
    volumes:
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
